package app.tastile.android.domain.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.json.JsonObject

/**
 * Pure-Kotlin domain model of a tile, decoupled from the data layer's
 * concrete repository class but field-compatible with
 * [app.tastile.android.data.model.Tile] so the Hilt adapter can do a
 * straightforward field-by-field translation at the boundary.
 *
 * Use cases and ViewModels must never import `data.model.Tile` (R23
 * architecture rule: domain is framework/data independent). Field
 * semantics mirror the data layer; KDoc on each field documents the
 * underlying v1 wire shape.
 */
data class Tile(
    /** Cloud-side tile id (UUID from `GET /v1/tiles`). */
    val id: String = "",
    /** Owning user id (UUIDv5 derived from Cognito `sub`). */
    @SerialName("user_id") val userId: String = "",
    /** Locally-cached id, usually the same as [id]; kept for snapshot row compatibility. */
    @SerialName("local_tile_id") val localTileId: String = "",
    /** Human-readable title shown in lists and detail screens. */
    val title: String = "",
    /** Optional "what to do next" prompt surfaced when the tile is active. */
    @SerialName("next_action") val nextAction: String? = null,
    /** Optional acceptance criteria the user defined for "done". */
    @SerialName("done_definition") val doneDefinition: String? = null,
    /** Lifecycle string from `GET /v1/tiles` (`Ready`/`Started`/`Done`/`Archived`). */
    val lifecycle: String = "Ready",
    /** Free-form labels attached to the tile. */
    val labels: List<String> = emptyList(),
    /** Minutes already worked on this tile (null when the tile has never been started). */
    @SerialName("worked_minutes") val workedMinutes: Long? = null,
    /** Minutes spent on break for this tile (null when no break recorded). */
    @SerialName("break_minutes") val breakMinutes: Long? = null,
    /** Backend numeric code for the objective mode (null = unset / legacy). */
    @SerialName("objective_mode_code") val objectiveModeCode: Int? = null,
    /** Target work minutes per cycle (null = no target). */
    @SerialName("target_work_min") val targetWorkMin: Long? = null,
    /** Target rest minutes per cycle (null = no target). */
    @SerialName("target_rest_min") val targetRestMin: Long? = null,
    /** Backend numeric code for the "done" rule (null = unset / legacy). */
    @SerialName("done_rule_code") val doneRuleCode: Int? = null,
    /** Optional note surfaced when the tile is resumed after a break. */
    @SerialName("resume_note") val resumeNote: String? = null,
    /** ISO-8601 instant the backend projects for the next scheduled start. */
    @SerialName("projected_next_start_at") val projectedNextStartAt: String? = null,
    /** ISO-8601 instant the tile becomes eligible again after being released. */
    @SerialName("release_at") val releaseAt: String? = null,
    /** ISO-8601 instant the tile is due. */
    @SerialName("due_at") val dueAt: String? = null,
    /** ISO-8601 instant for the fixed (pinned) start. */
    @SerialName("fixed_start") val fixedStart: String? = null,
    /** ISO-8601 instant for the fixed (pinned) end. */
    @SerialName("fixed_end") val fixedEnd: String? = null,
    /** ISO-8601 instant the active window opens (vs. fixed window). */
    @SerialName("active_start") val activeStart: String? = null,
    /** ISO-8601 instant the active window closes. */
    @SerialName("active_end") val activeEnd: String? = null,
    /** Id of the plan that owns this tile (null = no plan attached). */
    @SerialName("plan_id") val planId: String? = null,
    /** True when the tile is generated by a recurring rule. */
    @SerialName("is_recurring") val isRecurring: Boolean = false,

    // Legacy v0 condition slots. Kept for snapshot-row decoding and will be
    // retired once every consumer migrates to the new fields above.
    @SerialName("temporal_conditions") val temporalConditions: JsonObject? = null,
    @SerialName("objective_conditions") val objectiveConditions: JsonObject? = null,
    @SerialName("interruption_conditions") val interruptionConditions: JsonObject? = null,
    @SerialName("automation_conditions") val automationConditions: JsonObject? = null,
    @SerialName("annotation_conditions") val annotationConditions: JsonObject? = null,
    /** ISO-8601 instant the tile was created. */
    @SerialName("created_at") val createdAt: String? = null,
    /** ISO-8601 instant the tile was last updated. */
    @SerialName("updated_at") val updatedAt: String? = null,
    /** Local mirror of `created_at` from the v0 on-device cache. */
    @SerialName("local_created_at") val localCreatedAt: String? = null,
    /** Local mirror of `updated_at` from the v0 on-device cache. */
    @SerialName("local_updated_at") val localUpdatedAt: String? = null,
    /** Soft-delete tombstone instant (null = not deleted). */
    @SerialName("deleted_at") val deletedAt: String? = null,
)
